
java_binary(
  name = 'jdemo_gson',
  srcs = glob(
  [
    "src/com/demo/*.java",

  ]),
  main_class = "com.demo.Main",
  deps = [
    "@maven//:com_google_inject_guice",
    "@maven//:com_google_code_gson_gson",
  ],
)
